language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:

services:
  - rabbitmq

before_script:
  - curl -s http://getcomposer.org/installer | php && php composer.phar install --dev
  - pyrus channel-discover pear.symfony.com
  - pyrus install -o pear.phpunit.de/PHPUnit
  - pyrus install -o pear.phpunit.de/DbUnit
  - phpenv rehash
  - sudo apt-get install -y librabbitmq-dev
  - wget http://pecl.php.net/get/amqp-1.2.0.tgz
  - tar -xzf amqp-1.2.0.tgz
  - sh -c "cd amqp-1.2.0 && phpize && ./configure && make && sudo make install"
  - echo "extension=amqp.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: cd tests && phpunit -v --configuration phpunit.xml.travis
