language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:

services:
  - rabbitmq

before_script:
  - curl -s http://getcomposer.org/installer | php && php composer.phar install --dev
  - phpenv rehash
  - sudo apt-get install -y librabbitmq-dev
  - wget http://pecl.php.net/get/amqp-1.4.0.tgz
  - tar -xzf amqp-1.4.0.tgz
  - sh -c "cd amqp-1.4.0 && phpize && ./configure && make && sudo make install"
  - echo "extension=amqp.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: cd tests && ../vendor/bin/phpunit -v --configuration phpunit.xml.travis
